### ISSUE TITLE
External light selection

### ISSUE THREAD

**Issue by lespatots** [nidayand/node-red-contrib-tradfri#10]
In the OUT node would it be possible to allow the bulb to be selected through the Topic if no light (zero) is selected. This allows control via MQTT or from a database which might hold scenes or information on other lights driven through an alternate node (Hue for example)?

**Comment by thunder-62** [comment]
have you tried to use the msg.tradfri_id to dynamically address a bulb?

**Comment by nidayand** [comment]
As per @thunder-62 it should work as described. Please re-open the issue if it doesn't work. Thanks
