### ISSUE TITLE
Unable to generate Preshared Key

### ISSUE THREAD

**Issue by SteveRMann** [nidayand/node-red-contrib-tradfri#18]
No matter what I use for the App Identity, Node-Red returns "Registration did not work".
NEVER MIND...  I reset the router and the Gateway did return the Preshared Key.

**Comment by tbowmo** [comment]
I ended up registrering a user manually, using the info given here https://github.com/nidayand/node-red-contrib-tradfri/issues/11#issuecomment-341075124

**Comment by scholi** [comment]
For me the problem was that I put the path of the folder, not of the client binary
