### ISSUE TITLE
cant get preshared key

### ISSUE THREAD

**Issue by realjax** [nidayand/node-red-contrib-tradfri#21]
So, bit confused here, what am I supposed to do?
Fill in the path? or  fill in the path + name of executable? then press that 'get preshared...' button ?

should I expect some form of output?  Nothing happens for me. No error nothing.. Tried all differents sorts of things.

![screen shot 2018-06-02 at 17 54 08](https://user-images.githubusercontent.com/883435/40878204-fe054a2e-668d-11e8-9de6-3ee49ffc614d.PNG)

**Comment by realjax** [comment]
it cant connect to whatever it needs to connect to.
saw a bunch of these error messages in the chrome console:
Cannot GET /tradfri/register

**Comment by orandaadnaro** [comment]
Same problem here, with no pre-shared key generated or visible in the node-red information panel

**Comment by orandaadnaro** [comment]
I'm hoping that with new Trådfri products about to be released that someone will be working on a fix for the preshared key problem. If not there will be a growing number of node-red users using home assistant who will be sorely disappointed this won't work!

**Comment by realjax** [comment]
If Ikea's work on their app is anything to go by  then don't keep your hopes up. They'll add support for their new hardware and that's it.

orandaadnaro <notifications@github.com> schreef op 8 oktober 2018 20:29:11 CEST:
>I'm hoping that with new Trådfri products about to be released that
>someone will be working on a fix for the preshared key problem. If not
>there will be a growing number of node-red users using home assistant
>who will be sorely disappointed this won't work!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nidayand/node-red-contrib-tradfri/issues/21#issuecomment-427934988

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by nidayand** [comment]
It's the link to the CoAP library that is the binary that talks the Zigbee protocol. I've precompiled a few that are included with the node library. As described in the node info.
