### ISSUE TITLE
Module not loading

### ISSUE THREAD

**Issue by muracz** [nidayand/node-red-contrib-tradfri#4]
Hello, 
I have a strange problem. I try running the module on Node-Red:
Raspberry 2 - Debian
Node-RED version: v0.15.3
Node.js  version: v0.10.29
Linux 4.1.17-v7+ arm LE

While installing I see no errors but when I restart Node-Red I see the following error messages:

> Jul 10 22:27:04 domoticz Node-RED[29186]: /home/node-red/node_modules/node-red-contrib-tradfri/tradfri-out.js:23
> Jul 10 22:27:04 domoticz Node-RED[29186]: node.hub.tradfri.getDevice(msg.payload).then(device => {
> Jul 10 22:27:04 domoticz Node-RED[29186]: ^
> Jul 10 22:35:32 domoticz Node-RED[29646]: 10 Jul 22:35:32 - [warn] [tradfri-out] SyntaxError: Unexpected token >

Did I miss some prerequisites? 

Thanks in advance 
Marcin

**Comment by ukmoose** [comment]
The underlying library https://github.com/nidayand/node-tradfri-argon requires  Node.js 4.x +
If you wish to upgrade theres a script as part of the node-red upgrade instructions on their website

**Comment by muracz** [comment]
Thanks @ukmoose , somehow I missed how ancient my nodejs is :/ 

The standard update-nodejs-and-nodered script done the job perfectly.
