### ISSUE TITLE
404 error when searching for tradfi device 

### ISSUE THREAD

**Issue by alexschwantes** [nidayand/node-red-contrib-tradfri#6]
I've set up the config correctly and can use the tradfri get node to get and set states of lights (by passing msg.payload and the tradfri_id)

However the Device property on the tradfri-out node never updates. I click the refresh button but the icon just spins and never updates. When I click it I get a 404 error in the console for the url /tradfri/controls?sid=xxxxx&coap=%2Fhome%2Fpi%2Flibcoap%2Fexamples%2Fcoap-client&hubip=192.168.1.xx

RPI 3B raspbian
Node-RED version: v0.16.1
Node.js  version: v6.9.4
Linux 4.4.38-v7+ arm LE

**Comment by nidayand** [comment]
SHould work if your values are set correctly. With the new hub update, test the new release 1.1.0. As this is done client-side, what browser and version are you using? Have you tested with another browser?

**Comment by nidayand** [comment]
No response. Closing
