### ISSUE TITLE
Group status (on) and brightness incorrect in json

### ISSUE THREAD

**Issue by alexschwantes** [nidayand/node-red-contrib-tradfri#7]
When retrieving the complete structure from the tradfri get node, the following properties are always the same, regardless of the actual status of the group:
on: true
brightness: 0

The devices within the group show the correct values for on and brightness, just not the parent group in the returned json.

**Comment by nidayand** [comment]
A group is not a device itself hence it does not hold a state. What should a group state if one of the devices differs from the others? And this belongs to the argon library and not the tradfri lib so please register an request in that repo and the expected behaviour. Thanks
